name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

env:
  GO_VERSION: '1.18'


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go build -v .

  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl proxy 4280:4280 _api.internal -a acctestapp &
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN_CI }}
      - uses: actions/checkout@v3
      - run: go mod download
      - env:
          TF_ACC: "1"
          FLY_TF_TEST_APP: acctestapp
          FLY_API_TOKEN: ${{ secrets.FLY_AUTH_TOKEN_CI }}
        run: go test -v -cover ./internal/provider/
        timeout-minutes: 10
